name: 'Poetry cache action'
description: 'Action to handle poetry caching, with utilities to handle tricky cases'
author: 'Allan Chain'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  cache-key-prefix:
    required: false
    description: 'custom key prefix for @actions/cache, in addition to platform and poetry version'
    default: 'poetry'
  ensure-module:
    required: false
    description: 'make sure this module can be imported after installation, default pytest'
    default: 'pytest'
  install-args:
    required: false
    description: 'any args after `poetry install`. Seperated by spaces, as normally do in command line'
    default: ''
  replace-mirror:
    required: false
    description: 'replace mirror url, python-poetry/poetry#1632'
    default: ''
  working-directory:
    required: false
    description: 'working directory of the poetry project'
    default: '.'
  upload-strategy:
    required: false
    description: 'when to upload updated cache, `immediate` or `on-success`'
    default: 'immediate'
outputs:
  cache-hit:
    description: 'if "true", cache is restored from the exact cache key'
runs:
  using: 'node12'
  main: 'dist/main.js'
  post: 'dist/cleanup.js'
  post-if: 'success()'
