name: 'Poetry cache action'
description: 'Action to handle poetry caching, with utilities to handle tricky cases'
author: 'Allan Chain'
inputs:
  cache-key-prefix:
    required: false
    description: 'custom key prefix for @actions/cache, in addition to platform and poetry version'
    default: 'poetry'
  ensure-module:
    required: false
    description: 'make sure this module can be imported after installation, default pytest'
    default: 'pytest'
  install-root:
    required: false
    description: 'if "true", remain poetry default, else use `--no-root` when installing'
    default: 'true'
  replace-mirror:
    required: false
    description: 'python-poetry/poetry#1632'
    default: ''
  working-directory:
    required: false
    description: 'Working directory of th poetry project'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
