name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          path: action
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6
          run_install: true
      - name: Check Style
        working-directory: action
        run: |
          pnpm format-check
          pnpm lint
      - name: Build action
        working-directory: action
        run: pnpm build
      - name: Copy assets
        working-directory: action
        run: |
          mkdir public
          cp -r dist action.yml README.md LICENSE public
      - name: Checkout test repo
        uses: actions/checkout@v3
        with:
          repository: AllanChain/command4bot
          path: repo
      - uses: Gr1N/setup-poetry@v8
      - name: Test poetry-cache-action
        uses: ./action
        with:
          working-directory: repo
          install-args: --no-root
          cache-key-prefix: anything
          upload-strategy: on-success
      - name: Deploy to release
        if: github.ref == 'refs/heads/main' && github.actor == 'AllanChain'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./action/public
          publish_branch: release
          enable_jekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
